# Descriptive Statistics

## Purpose
This worksheet is an opportunity for you to practice calculating descriptive statistics. This is something you will need to do when reporting your results for our experiments. Some of the questions are purposely vague, because I would like you to think about them, and make a qualified decision about how to answer them.

## Part 1: Measures of central tendency.
The first block of code you can just copy and paste. If you need to, uncomment the ``pip intall`` sections.

In [19]:
# Just copy and paste this whole section into your notebook and run it.

#Install and import libraries

# Install packages if you need them
#%pip install pandas
%pip install seaborn
#%pip install scipy

# Import packages
import pandas as pd
import seaborn as sns

# read in the data from the url
url = 'https://raw.githubusercontent.com/ethanweed/ExPsyLing/refs/heads/master/experiments/masked_prime/data/combined_data.csv'
raw = pd.read_csv(url)                                                      # read in the data from the url

# make a list of all the columns we want to keep
cols = ['participant_id', 'sender', 'duration', 'prime', 'target', 'condition', 'soa_condition', 'congruence', 'response', 'correct_response']

# filter the data to keep only the columns we want, and only the rows we want
df = raw[cols]                                                             # make a new dataframe with only the columns in cols
df = df[df['sender'] == 'target']                                          # only keep the "target" rows
df = df[df['condition'] != 'practice']                                     # throw away the practice trials

# Some of the target words were labeled incorrectly in the original data, so we need to fix those.
incorrect_labels = ['LAND', 'TREE', 'BEAR', 'ROSE', 'HILL', 'DIRT', 'BULL', 'DUCK']
for word in incorrect_labels:
    df.loc[df['target'] == word, 'correct_response'] = 'n'                 # fix items with incorrect answer lables

df['correct'] = (df['response'] == df['correct_response']).astype(int)     # make a new column with 0 or 1 for incorrect / correct
df = df[df['correct'] == 1]                                                # keep only the correct responses   
df = df.rename(columns={'soa_condition': 'soa', 'duration': 'rt'})         # rename the soa and duration columns, just to look nicer

Requirement already satisfied: seaborn in /opt/conda/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/conda/lib/python3.13/site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in /opt/conda/lib/python3.13/site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/conda/lib/python3.13/site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)

Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

## Questions

1. How many participants are in the data?
2. On average, how long does it take participants to respond to the target words?
3. If another participant were to do this experiment, how long would you expect them to take to respond to target words with congruent primes?
4. If another participant were to do this experiment, how long would you expect them to take to respond to target words with incongruent primes?
5. Are you equally confident in your answers to the previous two questions? How could you quantify your confidence in your answers? 


Hints: 
1. These are questions about central tendency and variance.
2. There are different ways to quantify each of these. 
  a) Talk with each other about the different options, and what they mean.
  b) Plot the data, and use this to inform your choices.

Bonus (TOTALLY OPTIONAL, ONLY IF YOU RRALLY WANT TO):
These are response time data, and as we talked about back on September 23rd when we read Balota and Yap (2011), response time measures have a tendency to be skewed, rather than normally distributed. Investigate these data to see if they are indeed skewed, and if they are, try fitting an exgaussian distribution instead of a normal distribution for some more fine-tuned measures of central tendency:

```python
from scipy.stats import exponnorm

# Make a function to get the parameters of the ex-gaussian function for each participant and condition
def get_parameters(data):
    K, loc, scale = exponnorm.fit(data)
    tau = K * scale
    return pd.Series({'mu': loc,
                        'sigma': scale,
                        'tau': tau,
                        'mean': loc + tau})


# Use the function from above to get the parameters for each participant and condition
df_params = (
    df.groupby(['participant_id', 'congruence'])['rt']
    .apply(get_parameters)
    .unstack()
    .reset_index()
)

# Inspect the data
df_params.head()

```
Do these measures give you a better estimate the standard measures of central tendency?

In [20]:
df

,participant_id,sender,rt,prime,target,condition,soa,congruence,response,correct_response,correct
40,51,target,520.14,roof,PIANO,Inc_Synth_Synth,long,incongruent,m,m,1
47,51,target,640.66,sheep,BULL,Inc_Nat_Nat,long,incongruent,n,n,1
54,51,target,597.74,fort,GOAT,Inc_Synth_Nat,long,incongruent,n,n,1
61,51,target,495.68,pear,PEAR,Con_Nat,long,congruent,n,n,1
68,51,target,556.86,olive,MOTOR,Inc_Nat_Synth,long,incongruent,m,m,1
...,...,...,...,...,...,...,...,...,...,...,...
15606,69,target,699.20,belt,BELT,Con_Synth,short,congruent,m,m,1
15612,69,target,580.20,daisy,DAISY,Con_Nat,short,congruent,n,n,1
15618,69,target,577.90,peach,SHED,Inc_Nat_Synth,short,incongruent,m,m,1
15624,69,target,661.10,rake,HUSKY,Inc_Synth_Nat,short,incongruent,n,n,1
15630,69,target,709.20,fern,PETAL,Inc_Nat_Nat,short,incongruent,n,n,1

In [21]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_select_dtypes_indices',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'condition',
 'congruence',
 'convert_dtypes',
 'copy',
 'corr',
 'correct',
 'correct_response',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'participant_id',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prime',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'response',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rt',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'sender',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'soa',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'target',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [22]:
list(df)

['participant_id',
 'sender',
 'rt',
 'prime',
 'target',
 'condition',
 'soa',
 'congruence',
 'response',
 'correct_response',
 'correct']

In [23]:
#How many participants are in the data?
#On average, how long does it take participants to respond to the target words?
#If another participant were to do this experiment, how long would you expect them to take to respond to target words with congruent primes?
#If another participant were to do this experiment, how long would you expect them to take to respond to target words with incongruent primes?
#Are you equally confident in your answers to the previous two questions? How could you quantify your confidence in your answers?

In [24]:
#How many participants are in the data?
#df['participant_id'].unique()       #add len for length, to tell python to count the items in the list
len(df['participant_id'].unique())
#print(df['participant_id'].unique())

19

In [25]:
#On average, how long does it take participants to respond to the target words?
df.head()

,participant_id,sender,rt,prime,target,condition,soa,congruence,response,correct_response,correct
40,51,target,520.14,roof,PIANO,Inc_Synth_Synth,long,incongruent,m,m,1
47,51,target,640.66,sheep,BULL,Inc_Nat_Nat,long,incongruent,n,n,1
54,51,target,597.74,fort,GOAT,Inc_Synth_Nat,long,incongruent,n,n,1
61,51,target,495.68,pear,PEAR,Con_Nat,long,congruent,n,n,1
68,51,target,556.86,olive,MOTOR,Inc_Nat_Synth,long,incongruent,m,m,1

In [26]:
print(df[df['sender'] == 'target']['rt'].mean())

742.4425990348288

In [28]:
#If another participant were to do this experiment, how long
#would you expect them to take to respond to target words with congruent primes?
print(df[df['congruence'] == 'congruent']['rt'].mean())

723.748791628387

In [29]:
# question 4
print(df[df['congruence'] == 'incongruent']['rt'].mean())

761.7234543676751

In [32]:
# question 5 
import statistics as st
st.stdev(df)

TypeError: can't convert type 'str' to numerator/denominator

## Part 2: Correlation

Copy and paste the code below to load the data from the MEGALEX study [<sup id="fn1-back">1</sup>](#fn1) by Ferrand et al (2017)[<sup id="fn2-back">2</sup>](#fn2). These data include (among other things) word recognition response times, word length data, and frequency data.

In [33]:
url = 'https://raw.githubusercontent.com/ethanweed/datasets-for-teaching/refs/heads/main/MEGALEX.csv'
df = pd.read_csv(url)
df.head()

,item,n_trials,err,rt,sd,rtz,n_used,c_freq_movies,lc_freq_movies,c_freq_books,lc_freq_books,n_letters,n_syllables
0,abaissa,25,0.04,721.833333,106.416191,-0.035017,24,0.00,#NAME?,2.64,0.421603927,7,3
1,abaissait,25,0.08,836.782609,257.778086,0.366517,23,0.02,-1.698970004,2.50,0.397940009,9,3
2,abaissant,26,0.00,773.840000,224.378713,0.254392,25,0.04,-1.397940009,2.77,0.442479769,9,3
3,abaisse,25,0.04,698.826087,246.667913,-0.216788,23,1.30,0.113943352,3.45,0.537819095,7,2
4,abaissé,25,0.00,656.782609,177.024897,-0.434544,23,0.77,-0.113509275,1.55,0.190331698,7,3

Here is what the headers refer to.

| Column Header | Meaning |
|---|---|
| item | The specific word or stimulus being tested |
| n_trials | The total number of trials conducted for that item |
| err | The accuracy rate or error percentage for the item |
| rt | The reaction time or response time for the item |
| sd | The standard deviation of the reaction times |
| rtz | The standardised reaction time |
| n_used | The number of participants whose data was used for the item |
| c_freq_movies | The cumulative frequency of the word in movie subtitles |
| lc_freq_movies | The logarithmic cumulative frequency of the word in movie subtitles |
| c_freq_books | The cumulative frequency of the word in books |
| lc_freq_books | The logarithmic cumulative frequency of the word in books |
| n_letters | The number of letters in the word |
| n_syllables | The number of syllables in the word |

In [34]:
print(df['n_letters'].corr(df['c_freq_books']))

-0.09147595866662066

## Questions

1. Is there a relationship between word length and word frequency?
2. Does it make a difference if frequency is measured by looking at books or movies?
3. Does the frequency of the word affect your confidence in your estimate of how long people take to recognize it?

Hint: These are all questions about correlation.

### Footnotes

[<sup id="fn1">1</sup>](#fn1-back) Ferrand, L., Méot, A., Spinelli, E., New, B., Pallier, C., Bonin, P., Dufau, S., Mathôt, S., & Grainger, J. (2017). MEGALEX: A megastudy of visual and auditory word recognition. *Behavior Research Methods*.
  
[<sup id="fn2">2</sup>](#fn2-back) [OpenSesame](https://osdoc.cogsci.nl) fans may notice that Sebastian Mathôt is one of the authors of this study.